export const GET_SINGLE_DATA_REQ='GET_SINGLE_DATA_REQ';
export const GET_SINGLE_DATA_SUCC='GET_SINGLE_DATA_SUCC';
export const GET_SINGLE_DATA_FAIL='GET_SINGLE_DATA_FAIL';
export const DATA_CLEAN='DATA_CLEAN';